config/routes.rb
Students::Application.routes.draw do
  resources :students, :only => [:index, :show]

  student_check_path = "check/:lastname/:firstname/:patronymic/:group/:born_on"
  get student_check_path => "students#check", constraints: { born_on: /.+/ }

  mount API::Students => '/api'

  root to: "students#index"
end

app/models/student.rb
# encoding: utf-8

class Student < Model
  attribute :study_id
  attribute :person_id
  attribute :previous_person_id
  attribute :firstname
  attribute :patronymic
  attribute :lastname
  attribute :gender
  attribute :born_on, type: Date
  attribute :citizenship
  attribute :begin_study
  attribute :end_study
  attribute :learns
  attribute :in_gpo
  attribute :group
  attribute :zach_number
  attribute :financing
  attribute :activate_date
  attribute :student_state

  attribute :education

  delegate :group, :subfaculty, :faculty, :course, :speciality, to: :education

  normalize_attribute :firstname, :patronymic, :lastname, :group

  def name
    [lastname, firstname, patronymic].compact.join(' ')
  end

  def to_param
    study_id
  end

  def hostel_data
    Contingent.instance.student_hostels(self)
  end

  def orders_data
    url = [
      Settings['card_info.url'],
      "&contingentID=",
      person_id,
    ].join
    resource = RestClient::Resource.new(
      url, Settings['card_info.login'], Settings['card_info.pass']
    )
    response = resource.get

    Hashie::Mash.new(JSON.load(response.body)).orders
  end

  def self.from(hash)
    Student.new(
      study_id: hash[:study_id],
      person_id: hash[:person_id],
      previous_person_id: hash[:previous_person_id],
      firstname: hash[:first_name],
      patronymic: hash[:middle_name],
      lastname: hash[:last_name],
      gender: hash[:sex].gsub('М', 'мужской').gsub('Ж', 'женский'),
      born_on: hash[:birth_date],
      education: Education.new(hash[:education].merge(hash[:group])),
      begin_study: %(01.09.#{hash[:group][:year_forming]}),
      end_study: hash[:student_state][:name] == 'Окончил' ? I18n.l(hash[:activate_date]) : nil,
      learns: hash[:student_state][:name] == 'Активный',
      in_gpo: hash[:gpo],
      zach_number: hash[:zach_number],
      activate_date: hash[:activate_date],
      citizenship: hash[:citizenship][:name],
      student_state: hash[:student_state][:name],
      financing: hash[:financing]
    )
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  helper_method :search, :student, :students

  def index
  end

  def show
  end

  private

  def students
    @students = if search.include_aspirants?
                    Aspirant.collection(params[:search])
                  else
                    Contingent.instance.students(search)
                  end
  end

  def student
    Contingent.instance.find_student_by_study_id(params[:id])
  end

  def search
    @search ||= Search.new(params[:search])
  end

end

app/views/students/_aspirant.html.erb
<tr>
  <td><%= index + 1 %></td>
  <td><%= student.person_id %></td>
  <td>
    <%= student.lastname %>
  </td>
  <td>
    <%= student.firstname %>
  </td>
  <td>
    <%= student.patronymic %>
  </td>
  <td><%= student.born_on %></td>
  <td><%= student.group.number %></td>
  <td><%= student.group.course %></td>
  <td>
    <abbr title="<%= student.group.subfaculty.name %>">
      <%= student.group.subfaculty.abbr %>
    </abbr>
  </td>
  <td>
    <abbr title="<%= student.group.subfaculty.faculty.name %>">
      <%= student.group.subfaculty.faculty.abbr %>
    </abbr>
  </td>
  <td>
    <abbr title="<%= student.group.speciality.name %>">
      <%= student.group.speciality.code %>
    </abbr>
  </td>
  <td><%= student.learns %></td>
  <td><%= student.financing %></td>
</tr>

app/views/students/_form.html.erb
<%= simple_form_for search, url: '', html: { method: :get } do | form | %>
  <%= form.input :lastname, input_html: { class: "focus_first" } %>
  <%= form.input :firstname %>
  <%= form.input :patronymic %>
  <%= form.input :group %>
  <%= form.input :person_id %>
  <%= form.input :previous_person_id %>
  <%= form.input :include_inactive, as: :boolean %>
  <%= form.input :include_aspirants, as: :boolean %>

  <%= form.button :submit, 'Искать', class: 'button', name: nil %>
  <%= link_to 'Очистить', root_path, class: 'button' %>
<% end %>

app/views/students/_student.html.erb
<tr>
  <td><%= index + 1 %></td>
  <td><%= link_to student.study_id, student_path(student.study_id) %></td>
  <td><%= link_to student.person_id, students_path(search: { person_id: student.person_id, include_inactive: 1 }) %></td>
  <td><%= student.previous_person_id %></td>
  <td><%= student.lastname %></td>
  <td><%= student.firstname %></td>
  <td><%= student.patronymic %></td>
  <td><%= I18n.l student.born_on %></td>
  <td><%= student.group %></td>
  <td><%= student.course %></td>
  <td>
    <abbr title="<%= student.subfaculty.name %>">
      <%= student.subfaculty.abbr %>
    </abbr>
  </td>
  <td>
    <abbr title="<%= student.faculty.name %>">
      <%= student.faculty.abbr %>
    </abbr>
  </td>
  <td>
    <abbr title="<%= student.speciality.name %>">
      <%= student.speciality.code %>
    </abbr>
  </td>
  <td><%= yes_no student.in_gpo %></td>
  <td><%= yes_no student.learns %></td>
  <td><%= student.financing %></td>
</tr>

app/views/students/index.html.erb
<h1>Список студентов</h1>

<%= render 'form' %>

<% if students.any? %>
  <table class='tablesorter'>
    <thead>
      <tr>
        <th>№</th>
        <th>ID</th>
        <% if params['search']['include_aspirants'] != '1' %>
          <th>Person ID</th>
          <th>Prev Person ID</th>
        <% end %>
        <th>Фамилия</th>
        <th>Имя</th>
        <th>Отчество</th>
        <th>Дата рождения</th>
        <th>Группа</th>
        <th>Курс</th>
        <th>Кафедра</th>
        <th>Факультет</th>
        <th>Специальность</th>
        <% if params['search']['include_aspirants'] != '1' %>
          <th>В ГПО</th>
        <% end %>
        <th>Учится</th>
        <th>Бюджет/ПВЗ</th>
      </tr>
    </thead>
    <tbody>
    <% students.each_with_index do |student, index| %>
      <% if params['search']['include_aspirants'] == '1' %>
        <%= render partial: 'aspirant', locals: { index: index, student: student } %>
      <% else %>
        <%= render partial: 'student', locals: { index: index, student: student } %>
      <% end %>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/students/show.html.erb
<h1>Студент</h1>
<%= show_for student do | student | %>
  <%= student.attributes :study_id, :person_id, :previous_person_id %>
  <%= student.attributes :name, :gender, :born_on, :citizenship %>
  <%= student.association :faculty %>
  <%= student.association :subfaculty %>
  <%= student.association :speciality do %>
    <%= student.object.speciality.kind %>,
    <%= student.object.speciality.code %>
    <%= student.object.speciality.name %>
  <% end %>
  <%= student.attributes :begin_study, :end_study %>
  <%= student.attributes :course, :group %>
  <%= student.attributes :learns, :activate_date, :student_state %>
  <%= student.attributes :zach_number %>
  <%= student.attributes :in_gpo, :financing %>
<% end %>

<% if student.hostel_data.any? %>
  <h4>Общежития</h4>
  <% student.hostel_data.each do |hostel_living| %>
    <p><strong>Общежитие:</strong> <%= hostel_living.hostel[:name] %></p>
    <p><strong>Комната:</strong> <%= hostel_living.room_number %></p>
    <p><strong>Начало:</strong> <%= hostel_living.start_date %></p>
    <p><strong>Окончание:</strong> <%= hostel_living.end_date %></p>
    <hr />
  <% end %>
<% end %>

<% if student.orders_data.any? %>
  <h4>Приказы</h4>
  <% student.orders_data.each do |order| %>
    <p>№ <%= order.numb %> от <%= order.date %></p>
    <p><%= order.title %></p>
    <hr />
  <% end %>
<% end %>

<p><%= link_to 'Вернуться', :back, class: "button" %></p>